"""Init DogEntity ml_service

Revision ID: f2ef36469e99
Revises: 
Create Date: 2026-04-20 16:41:58.407350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2ef36469e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Breed1', sa.Integer(), nullable=False),
    sa.Column('Breed2', sa.Integer(), nullable=False),
    sa.Column('Gender', sa.Integer(), nullable=False),
    sa.Column('MaturitySize', sa.Integer(), nullable=False),
    sa.Column('FurLength', sa.Integer(), nullable=False),
    sa.Column('Vaccinated', sa.Integer(), nullable=False),
    sa.Column('Dewormed', sa.Integer(), nullable=False),
    sa.Column('Sterilized', sa.Integer(), nullable=False),
    sa.Column('Health', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Fee', sa.Integer(), nullable=False),
    sa.Column('PhotoAmt', sa.Integer(), nullable=False),
    sa.Column('VideoAmt', sa.Integer(), nullable=False),
    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('AdoptionSpeed', sa.Integer(), nullable=True),
    sa.Column('dog_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ml_service'
    )
    op.create_index(op.f('ix_ml_service_dogs_dog_service_id'), 'dogs', ['dog_service_id'], unique=True, schema='ml_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_service_dogs_dog_service_id'), table_name='dogs', schema='ml_service')
    op.drop_table('dogs', schema='ml_service')
    # ### end Alembic commands ###
